config/routes.rb
TravelClient::Application.routes.draw do
  resources :temps


  	match "/fb", :to => 'get_token#index', :via => :GET

	root :to => 'start#index'
	match '/callback', :to => 'get_token#callback', :via => :GET
	match '/test', :to => 'get_token#test', :via => :GET
	match '/reset', :to => 'reset#index', :via => :GET
	match '/last', :to => 'last#index', :via => :POST
	match '/no_fb', :to => 'no_fb#index', :via => :POST
	match '/wofbseat',:to => 'without_fb#index',:via => :GET
end

app/models/seat.rb
class Seat
  include Mongoid::Document
  def self.reset
  	i=1
		Seat.delete_all
		sd={}
		while i<=40  do
			sd[('s'+i.to_s).to_sym]={:occupied => false}
			i+=1
		end
		Seat.new(sd).save
  end
  def self.reserve_seat(sid,token=nil)
  	sd=Seat.all.first.attributes
    
    # raise 'alok'
  	Seat.delete_all
  	 if !token.nil?
  		sd[sid.to_sym]={
  			:occupied => true,
  			:fb => token
  		}
	   else
	     sd[sid.to_sym]={
  			:occupied => true
  		  }	
  	 end
  	Seat.new(sd).save	
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/get_token_controller.rb
require 'net/http'
class GetTokenController < ApplicationController
	def index
		appid = "1408221636130524"
		appsecret = "fe78228de0d214b0117cd2cd3cae645e"
		callbackurl = "http://localhost:3000/callback"
		$oauth = Koala::Facebook::OAuth.new(appid, appsecret, callbackurl)

		redirect_to $oauth.url_for_oauth_code(
			:permissions => "user_about_me,user_likes,user_interests,user_friends"
		)
	end

	def callback
		sd=Seat.all.first.attributes
		sd.shift
		@code = $oauth.get_access_token(params[:code])
		#raise 'alok'
		uri = URI('http://localhost:4000/api')
		res = Net::HTTP.post_form(uri,:user_token => @code,:seat_data => sd.to_json,:adjacency_data => $adjacency_data.to_json)
	    @response=res.body	
	end	
end

app/controllers/last_controller.rb
class LastController < ApplicationController
	def index
			Seat.reserve_seat(params[:seatno],params[:token])
	end	
end

app/controllers/no_fb_controller.rb
class NoFbController < ApplicationController
	def index
			Seat.reserve_seat(params[:seatno])
			render json:done
	end	
end

app/controllers/reset_controller.rb
class ResetController < ApplicationController
	def index
		Seat.reset

		render json:"done"
	end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index

  end
end

app/controllers/without_fb_controller.rb
class WithoutFbController < ApplicationController
	def index
		sd=Seat.all.first.attributes
		sd.shift
		@response = {}
		sd.each do |k,v|
			if v["occupied"] == true
				@response[k] = -1
			else
				@response[k] = 0
			end
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_token_helper.rb
module GetTokenHelper
end

app/helpers/last_helper.rb
module LastHelper
end

app/helpers/no_fb_helper.rb
module NoFbHelper
end

app/helpers/reset_helper.rb
module ResetHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/without_fb_helper.rb
module WithoutFbHelper
end

app/views/get_token/callback.html.erb
<script type="text/javascript" src="jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="jquery.qtip-1.0.0-rc3.min.js"></script>
<body>
  <table>
    <tr>
    <td>
    <% @response = JSON.parse(@response) %>
    <table>
      <% @response.each_slice(5) do |_e| %>
        <tr>
        <td width="100"></td>
        <% _e.each_slice(3) do |e| %>
          <% e.each do |k,v| %>
            <td>
              <img src="images.jpg" height="80" width="80" id="<%= k %>"/>
            </td>


          <% end %>
          <td width="100"></td>
        <% end %>
        </tr>
      <% end %>
    </table>
    </td>
    <td>
      <% z=100 %>
      <% @response.each do |k,v| %>
        <% if v.is_a?Numeric %>
        <% if v<0 %>
          <div id="t<%= k %>" style="height:200px;width:350px;z-index:<%= z %>;display:none;border:1px solid black">
            <p>
              Occupied, No Facebook Data
            </p>
          </div>
        <% else %>
          <div id="t<%= k %>" style="height:200px;width:350px;z-index:<%= z %>;display:none;border:1px solid black">
            <p>
              Unoccupied, Click to select Seat
            </p>
          </div>
        <% end %>
        <% else %>
          <div id="t<%= k %>" style="height:200px;width:350px;z-index:<%= z %>;display:none;border:1px solid black">
            <p>
              <table>
              <tr height="50">
              <td width="175">
              <center><%= @response[k]["co_name"] %></center>
              </td>
              <td width="175">
              <center>
              <% i=3 %>
              <% @response[k]["matched_likes"].each do |x| %>
              <%= x %>
              <% if i==0 %>
              <%break%>
              <% end %>
              <% i=i-1 %>
              <% end %>
              </center>
              </td>
              </tr>
              <tr height="150">
              <td width="175">
              <img src="<%= @response[k]["co_image"] %>" height="125" width="125"style="margin-bottom:25px;" >
              </td>
              <td width="175">
              <!-- graph -->
              </td>
              </tr>
              </table>
            </p>
          </div>
        <% end %>
        <% z = z+1 %>
      <% end %>
    </td>
    </tr>
  </table>
  <%= form_tag '/last' do %>
    <%= text_field_tag :seatno %>
    <%= hidden_field_tag :token, @code %>
    <%= submit_tag 'submit' %>
  <% end %>
</body>

<% @response.each do |k,v| %>
<script>
$(function(){
    $("#<%= k %>").hover(function(){
    $("#t<%= k %>").css('display', 'inline-block');
    }, function(){
        $("#t<%= k %>").css('display', 'none');
    });
});
</script>
<% end %>

app/views/last/index.html.erb
<html>
abhinav
</html>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Travel Api" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Travel Api" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
       <%= render 'layouts/messages' %>
       <%= yield %>
  </body>
</html>

app/views/start/index.html.erb
<!DOCTYPE html>
<html>
<body>
<center><h2>Login through Facebook</h2>
<%= link_to 'Login',:controller => 'get_token', :method => 'index' %>
<h2>OR</h2>
DUMMY
</center></center>
</body>
</html>

app/views/temps/_form.html.erb
<%= form_for(@temp) do |f| %>
  <% if @temp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temp.errors.count, "error") %> prohibited this temp from being saved:</h2>

      <ul>
      <% @temp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temps/edit.html.erb
<h1>Editing temp</h1>

<%= render 'form' %>

<%= link_to 'Show', @temp %> |
<%= link_to 'Back', temps_path %>

app/views/temps/index.html.erb
<h1>Listing temps</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @temps.each do |temp| %>
  <tr>
    <td><%= temp.name %></td>
    <td><%= link_to 'Show', temp %></td>
    <td><%= link_to 'Edit', edit_temp_path(temp) %></td>
    <td><%= link_to 'Destroy', temp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Temp', new_temp_path %>

app/views/temps/new.html.erb
<h1>New temp</h1>

<%= render 'form' %>

<%= link_to 'Back', temps_path %>

app/views/temps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @temp.name %>
</p>


<%= link_to 'Edit', edit_temp_path(@temp) %> |
<%= link_to 'Back', temps_path %>

app/views/without_fb/index.html.erb
<html>
<center>
<%= @response %>
<h2>Enter the seat number :<h2>
<%= form_tag('/no_fb') do %>
<%= text_field_tag :seatno  %><br>
<%= submit_tag "submit" %>
<% end %>
</center>
<html>